### ISSUE TITLE
About validation

### ISSUE THREAD

**Issue by aajour** [facg3/NewMusicAPI-#27]
https://github.com/facg3/NewMusicAPI-/blob/d3e9f09d00e65de9dbcc0a1cf64f9683b77aa4c8/JS/logic.js#L38

I like how you using the empty field validation :+1: , but I prefer not to use `JS alert` for many reasons
like It's annoying, stops the entire browser and needing extra action to do (click)

> Instead, highlight the erroneous fields/values, and print a message at the top, explaining that the highlighted fields need to be corrected before the user can continue.

**Comment by MMortaga** [comment]
Alright! Thanks a lot Ahmad, we'll fix this in a moment!
